In [26]:
import pandas as pd
import numpy as np

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
df = pd.read_csv("/content/drive/MyDrive/PML/Dataset/devnagari_db_csv.zip")

In [29]:
df.shape

(92000, 1025)

In [30]:
df.columns

Index(['pixel_0000', 'pixel_0001', 'pixel_0002', 'pixel_0003', 'pixel_0004',
       'pixel_0005', 'pixel_0006', 'pixel_0007', 'pixel_0008', 'pixel_0009',
       ...
       'pixel_1015', 'pixel_1016', 'pixel_1017', 'pixel_1018', 'pixel_1019',
       'pixel_1020', 'pixel_1021', 'pixel_1022', 'pixel_1023', 'character'],
      dtype='object', length=1025)

In [31]:
df["character"].unique()

array(['character_01_ka', 'character_02_kha', 'character_03_ga',
       'character_04_gha', 'character_05_kna', 'character_06_cha',
       'character_07_chha', 'character_08_ja', 'character_09_jha',
       'character_10_yna', 'character_11_taamatar', 'character_12_thaa',
       'character_13_daa', 'character_14_dhaa', 'character_15_adna',
       'character_16_tabala', 'character_17_tha', 'character_18_da',
       'character_19_dha', 'character_20_na', 'character_21_pa',
       'character_22_pha', 'character_23_ba', 'character_24_bha',
       'character_25_ma', 'character_26_yaw', 'character_27_ra',
       'character_28_la', 'character_29_waw', 'character_30_motosaw',
       'character_31_petchiryakha', 'character_32_patalosaw',
       'character_33_ha', 'character_34_chhya', 'character_35_tra',
       'character_36_gya', 'digit_0', 'digit_1', 'digit_2', 'digit_3',
       'digit_4', 'digit_5', 'digit_6', 'digit_7', 'digit_8', 'digit_9'],
      dtype=object)

In [32]:
df1 = df.loc[df["character"].isin(["character_24_bha","character_25_ma","character_26_yaw","character_17_tha","character_23_ba","character_29_waw"]),:]
df1.shape

(12000, 1025)

In [33]:
df1["character"].unique()

array(['character_17_tha', 'character_23_ba', 'character_24_bha',
       'character_25_ma', 'character_26_yaw', 'character_29_waw'],
      dtype=object)

In [25]:
X = df1.drop(columns=["character"])
Y = df1["character"]
print(X.shape)
print(Y.shape)

label_map={"character_17_tha":0,"character_23_ba":1,"character_24_bha":2,"character_25_ma":3,"character_26_yaw":4,"character_29_waw":5}
Y.replace(label_map,inplace=True)


from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=7,stratify=Y)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)



(12000, 1024)
(12000,)
(8400, 1024)
(3600, 1024)
(8400,)
(3600,)


/tmp/ipykernel_693/2386803610.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y.replace(label_map,inplace=True)
/tmp/ipykernel_693/2386803610.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y.replace(label_map,inplace=True)


In [34]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
model = LogisticRegression(random_state=7)
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

0.7858333333333334
[[476  21  27   8  58  10]
 [ 14 474   9  18  24  61]
 [ 11   5 516  37  22   9]
 [  8  28  35 475  32  22]
 [ 72  12  38  36 421  21]
 [ 17  55   5  17  39 467]]
              precision    recall  f1-score   support

           0       0.80      0.79      0.79       600
           1       0.80      0.79      0.79       600
           2       0.82      0.86      0.84       600
           3       0.80      0.79      0.80       600
           4       0.71      0.70      0.70       600
           5       0.79      0.78      0.78       600

    accuracy                           0.79      3600
   macro avg       0.79      0.79      0.79      3600
weighted avg       0.79      0.79      0.79      3600



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state = 7, oob_score = True,max_samples=0.8,max_features=1000)
rf.fit(X_train, Y_train)
Y_pred = rf.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

0.8902777777777777
[[523   5   8   3  48  13]
 [  7 527   9   3  10  44]
 [ 14   4 526  43   7   6]
 [  1   9  23 545  17   5]
 [ 31   0   3   7 548  11]
 [  8  21   2  13  20 536]]
              precision    recall  f1-score   support

           0       0.90      0.87      0.88       600
           1       0.93      0.88      0.90       600
           2       0.92      0.88      0.90       600
           3       0.89      0.91      0.90       600
           4       0.84      0.91      0.88       600
           5       0.87      0.89      0.88       600

    accuracy                           0.89      3600
   macro avg       0.89      0.89      0.89      3600
weighted avg       0.89      0.89      0.89      3600



In [24]:
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=50,max_depth=5,learning_rate=0.1,subsample=0.8,colsample=0.8,random_state=7)
xgb.fit(X_train, Y_train)
Y_pred = xgb.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:34:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782: 
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


0.925
[[564   6   3   4  18   5]
 [  6 536   1   8  13  36]
 [  7   3 559  24   5   2]
 [  1   9  19 552  14   5]
 [ 27   2   1   5 559   6]
 [  4  17   1   7  11 560]]
                  precision    recall  f1-score   support

character_17_tha       0.93      0.94      0.93       600
 character_23_ba       0.94      0.89      0.91       600
character_24_bha       0.96      0.93      0.94       600
 character_25_ma       0.92      0.92      0.92       600
character_26_yaw       0.90      0.93      0.92       600
character_29_waw       0.91      0.93      0.92       600

        accuracy                           0.93      3600
       macro avg       0.93      0.92      0.93      3600
    weighted avg       0.93      0.93      0.93      3600



In [43]:
from catboost import CatBoostClassifier
cbc = CatBoostClassifier(iterations=100,depth=5,learning_rate=0.2,cat_features=None,loss_function="MultiClass",random_state=7)
cbc.fit(X_train,Y_train,eval_set=(X_test,Y_test))
Y_pred = cbc.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

0:	learn: 1.5528045	test: 1.5561695	best: 1.5561695 (0)	total: 2.74s	remaining: 4m 31s
1:	learn: 1.4154003	test: 1.4190423	best: 1.4190423 (1)	total: 4.36s	remaining: 3m 33s
2:	learn: 1.3131167	test: 1.3250298	best: 1.3250298 (2)	total: 5.92s	remaining: 3m 11s
3:	learn: 1.2294930	test: 1.2466737	best: 1.2466737 (3)	total: 7.49s	remaining: 2m 59s
4:	learn: 1.1631525	test: 1.1834112	best: 1.1834112 (4)	total: 8.92s	remaining: 2m 49s
5:	learn: 1.1087566	test: 1.1306816	best: 1.1306816 (5)	total: 10.7s	remaining: 2m 47s
6:	learn: 1.0560095	test: 1.0831353	best: 1.0831353 (6)	total: 11.7s	remaining: 2m 36s
7:	learn: 1.0106893	test: 1.0388826	best: 1.0388826 (7)	total: 12.8s	remaining: 2m 27s
8:	learn: 0.9688586	test: 1.0008729	best: 1.0008729 (8)	total: 13.8s	remaining: 2m 19s
9:	learn: 0.9387975	test: 0.9728261	best: 0.9728261 (9)	total: 14.9s	remaining: 2m 14s
10:	learn: 0.9113573	test: 0.9482635	best: 0.9482635 (10)	total: 16s	remaining: 2m 9s
11:	learn: 0.8866678	test: 0.9238814	best: 0

In [50]:
import lightgbm as lgb
lgbm = lgb.LGBMClassifier(n_estimators=100,max_depth=5,learning_rate=0.2,subsample=0.8,colsample_bytree=0.8,random_state=7)
lgbm.fit(X_train,Y_train)
Y_pred = lgbm.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.400414 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 159611
[LightGBM] [Info] Number of data points in the train set: 8400, number of used features: 784
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM]

In [52]:
import lightgbm as lgb
lgbm = lgb.LGBMClassifier(n_estimators=50,max_depth=5,learning_rate=0.2,subsample=0.8,colsample_bytree=0.8,random_state=7)
lgbm.fit(X_train,Y_train)
Y_pred = lgbm.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.374050 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 159611
[LightGBM] [Info] Number of data points in the train set: 8400, number of used features: 784
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM]

In [53]:
import lightgbm as lgb
lgbm = lgb.LGBMClassifier(n_estimators=100,max_depth=5,learning_rate=0.5,subsample=0.8,colsample_bytree=0.8,random_state=7)
lgbm.fit(X_train,Y_train)
Y_pred = lgbm.predict(X_test)

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.403637 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 159611
[LightGBM] [Info] Number of data points in the train set: 8400, number of used features: 784
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Info] Start training from score -1.791759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM]