In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, mean_absolute_error,mean_squared_error, r2_score

In [ ]:
df = pd.read_csv("/content/medical expenses.csv").dropna()
df

,age,sex,bmi,children,smoker,region,expenses
0,19,female,27.9,0,yes,southwest,16884.92
1,18,male,33.8,1,no,southeast,1725.55
2,28,male,33.0,3,no,southeast,4449.46
3,33,male,22.7,0,no,northwest,21984.47
4,32,male,28.9,0,no,northwest,3866.86
...,...,...,...,...,...,...,...
1333,50,male,31.0,3,no,northwest,10600.55
1334,18,female,31.9,0,no,northeast,2205.98
1335,18,female,36.9,0,no,southeast,1629.83
1336,21,female,25.8,0,no,southwest,2007.95


In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.nunique().sum().sum()

np.int64(1673)

In [ ]:
df.isna().sum()

,0
age,0
sex,0
bmi,0
children,0
smoker,0
region,0
expenses,0


In [ ]:
cont_col = ["age","bmi"]

In [ ]:
df_ohe = pd.get_dummies(df)
df_ohe.shape

(1337, 12)

In [ ]:
X = df_ohe.drop("expenses",axis=1)
Y = df_ohe["expenses"]
X.shape, Y.shape

((1337, 11), (1337,))

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=7)
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((935, 11), (935,), (402, 11), (402,))

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[cont_col] = sc.fit_transform(X_train[cont_col])
X_test[cont_col] = sc.transform(X_test[cont_col])

In [ ]:
X_train[cont_col].mean()

,0
age,8.359326e-17
bmi,2.659786e-16


In [ ]:
lr = LinearRegression()
lr.fit(X_train,Y_train)
Y_pred = lr.predict(X_test)


In [ ]:
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 6210.2716157612385
mean absolute error: 4262.336281450989
r2_score : 0.7324133376864894


In [ ]:
lr.coef_

array([  3691.76308759,   2141.74157658,    550.95853205,     77.40983229,
          -77.40983229, -11932.614766  ,  11932.614766  ,    807.07943605,
           24.93368793,   -638.37864692,   -193.63447706])

In [ ]:
lr.intercept_

np.float64(19626.04536523765)

In [ ]:
# ploynomial regression
# 1.add ploy features in tha data
# 2.apply linear regression
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2)
X_train_poly = pf.fit_transform(X_train)
X_test_poly = pf.transform(X_test)

X_train_poly.shape, X_test_poly.shape

((935, 78), (402, 78))

In [ ]:
lr = LinearRegression()
lr.fit(X_train_poly,Y_train)
Y_pred = lr.predict(X_test_poly)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5164.675423679967
mean absolute error: 2963.5756733421345
r2_score : 0.8149328492092578


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pf3 = PolynomialFeatures(degree=3)
X_train_poly3 = pf3.fit_transform(X_train)
X_test_poly3 = pf3.transform(X_test)
X_train_poly3.shape, X_test_poly3.shape

((935, 364), (402, 364))

In [ ]:
lr = LinearRegression()
lr.fit(X_train_poly3,Y_train)
Y_pred = lr.predict(X_test_poly3)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5261.807789576539
mean absolute error: 3122.1429446805687
r2_score : 0.8079062515325234


In [ ]:
from sklearn.linear_model import Ridge, Lasso
ls = Lasso(alpha=1,random_state=7)
ls.fit(X_train_poly,Y_train)
Y_pred = ls.predict(X_test_poly)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5163.539814272533
mean absolute error: 2963.630309903382
r2_score : 0.8150142254332273


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.626e+08, tolerance: 1.380e+07
  model = cd_fast.enet_coordinate_descent(


In [ ]:
from sklearn.linear_model import Ridge, Lasso
rg = Ridge(alpha=1,random_state=7)
rg.fit(X_train_poly,Y_train)
Y_pred = rg.predict(X_test_poly)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5161.851912428195
mean absolute error: 2965.9433329455424
r2_score : 0.8151351451153899


In [ ]:
from sklearn.linear_model import Ridge, Lasso
ls = Lasso(alpha=1,random_state=7)
ls.fit(X_train_poly3,Y_train)
Y_pred = ls.predict(X_test_poly3)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5252.85949583102
mean absolute error: 3111.0686949540604
r2_score : 0.8085590498695285


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.758e+08, tolerance: 1.380e+07
  model = cd_fast.enet_coordinate_descent(


In [ ]:
from sklearn.linear_model import Ridge, Lasso
rg = Ridge(alpha=1,random_state=7)
rg.fit(X_train_poly3,Y_train)
Y_pred = rg.predict(X_test_poly3)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5253.060993101152
mean absolute error: 3116.5005623617185
r2_score : 0.8085443624145414


In [ ]:
# impact of alpha on regularization
# alpha controls how much of the penelty  affects total loss in L1

#LASSO
# default aplha = 1
# use high alpha ::

from sklearn.linear_model import Ridge, Lasso
ls = Lasso(alpha=0.5,random_state=7)
ls.fit(X_train_poly3,Y_train)
Y_pred = ls.predict(X_test_poly3)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5257.653477590329
mean absolute error: 3117.3549077340717
r2_score : 0.8082094561981368


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.475e+09, tolerance: 1.380e+07
  model = cd_fast.enet_coordinate_descent(


In [ ]:
(ls.coef_ !=0).sum(),(ls.coef_ == 0).sum()

(np.int64(147), np.int64(217))

In [ ]:
from sklearn.linear_model import Ridge, Lasso
rg = Ridge(alpha=50,random_state=7)
rg.fit(X_train_poly3,Y_train)
Y_pred = rg.predict(X_test_poly3)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5140.727855249266
mean absolute error: 3153.0285780720264
r2_score : 0.8166451091126958


In [ ]:
rg.coef_

array([    0.        ,   908.47886347,  1170.05457694,   132.69107054,
         -32.09420976,    32.09420976, -2112.90608063,  2112.90608063,
         187.20783025,   -90.25040742,   -42.6019531 ,   -54.35546973,
         186.2693733 ,    -9.45591171,   -82.97907211,   358.34489065,
         550.13397281,   494.26059506,   414.21826841,    54.27481875,
         229.01801153,   373.33641372,   251.84961946,   -71.83973524,
         103.76685007,   620.21482626,   549.83975068,  -943.12875596,
        2113.1833329 ,   260.09449411,   482.65155134,    92.39674714,
         334.91178435,   -23.23573252,   106.48730288,    26.20376766,
          79.62814729,    53.06292325,   233.49255411,   184.09961664,
        -150.49729529,  -134.40380492,   -32.09420976,     0.        ,
       -1016.52714647,   984.43293671,    67.07056576,    14.204182  ,
         -47.84377602,   -65.52518151,    32.09420976, -1096.37893416,
        1128.47314392,   120.13726449,  -104.45458942,     5.24182291,
      

In [ ]:
from sklearn.linear_model import Ridge, Lasso
rg = Ridge(alpha=0.5,random_state=7)
rg.fit(X_train_poly3,Y_train)
Y_pred = rg.predict(X_test_poly3)
print("root mean squared error:",root_mean_squared_error(Y_test,Y_pred))
print("mean absolute error:",mean_absolute_error(Y_test,Y_pred))
print("r2_score :",r2_score(Y_test,Y_pred))

root mean squared error: 5257.359271332407
mean absolute error: 3119.2919076773874
r2_score : 0.8082309199175329


In [ ]:
rg.coef_

array([ 0.00000000e+00,  1.07999938e+03,  1.49355547e+03,  1.72424943e+01,
       -6.40047928e+00,  6.40047928e+00, -2.49798050e+03,  2.49798050e+03,
        2.41383122e+02, -1.08399609e+02, -6.75447254e+01, -6.54387871e+01,
        4.39817304e+01,  3.38498382e+01, -2.27208096e+02,  4.06075443e+02,
        6.73923932e+02,  5.53958951e+02,  5.26040424e+02, -2.35506552e+00,
        2.75347240e+02,  5.34573167e+02,  2.72434033e+02, -1.89340623e+02,
       -1.22377354e+01,  7.66503986e+02,  7.27051485e+02, -1.22737102e+03,
        2.72092649e+03,  1.89721983e+02,  7.73706745e+02, -2.05552509e+01,
        5.50681993e+02,  7.13361088e+00,  9.57283749e+01, -7.84858807e+01,
        4.03681092e+02, -3.86438598e+02,  2.15525904e+02,  3.99095939e+02,
       -3.45543447e+02, -2.51835902e+02, -6.40047928e+00,  0.00000000e+00,
       -1.22943017e+03,  1.22302969e+03,  1.05461283e+02,  6.60946392e+01,
       -1.23608589e+02, -5.43478120e+01,  6.40047928e+00, -1.26855033e+03,
        1.27495081e+03,  

### Elastic Net Regression

In [193]:
from sklearn.linear_model import ElasticNet

# Initialize and fit the Elastic Net model
en = ElasticNet(alpha=0.5, l1_ratio=0.5, random_state=7)
en.fit(X_train_poly3, Y_train)

Y_pred_en = en.predict(X_test_poly3)

# Evaluate the Elastic Net model
print("Elastic Net Root Mean Squared Error:", root_mean_squared_error(Y_test, Y_pred_en))
print("Elastic Net Mean Absolute Error:", mean_absolute_error(Y_test, Y_pred_en))
print("Elastic Net R2 Score:", r2_score(Y_test, Y_pred_en))

Elastic Net Root Mean Squared Error: 5415.818387457782
Elastic Net Mean Absolute Error: 3621.5305885513235
Elastic Net R2 Score: 0.796496699553124


In [194]:
from sklearn.linear_model import ElasticNet

# Initialize and fit the Elastic Net model
en = ElasticNet(alpha=100, l1_ratio=0.5, random_state=7)
en.fit(X_train_poly3, Y_train)

Y_pred_en = en.predict(X_test_poly3)

# Evaluate the Elastic Net model
print("Elastic Net Root Mean Squared Error:", root_mean_squared_error(Y_test, Y_pred_en))
print("Elastic Net Mean Absolute Error:", mean_absolute_error(Y_test, Y_pred_en))
print("Elastic Net R2 Score:", r2_score(Y_test, Y_pred_en))

Elastic Net Root Mean Squared Error: 11041.261459325666
Elastic Net Mean Absolute Error: 8485.040091816443
Elastic Net R2 Score: 0.15417472110852326
